# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12
      uses: actions/setup-node@v3
      with:
        node-version: 12
        cache: 'npm'
    - run: npm ci
    - run: npm install -g @angular/cli@7.0.6
    - run: ng build --prod
    - run: npm prune --production
    - name: Set up ssh
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
    - name: Deploy
      run: |
        ls
        ls dist/netflix-activity
        ls dist/netflix-activity/netflix-activity
        ./linode-deployment/deploy.sh
      shell: bash
      env:
        SERVER: ${{secrets.SERVER_IP}}
        DEPLOY_USER: "github"
